<a href="https://colab.research.google.com/github/subir0071/Coursera_Intro_to_Tensorflow_for_AI/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#In this notebook we are going to cover some of the most fundamental concepts of tensors using Tensorflow

Introduction to Tensors

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [ ]:
# Check dimension of a vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],[34,6]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [34,  6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix of float datatypr
another_matrix = tf.constant([[10.,2.],
                              [20.,3.],
                              [30.,4.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [20.,  3.],
       [30.,  4.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([
                  [[1,2,3],
                   [4,5,6]],
                  [[7,8,9],
                   [10,11,12]],
                  [[13,14,15],
                   [16,17,18]]
                           ])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating tensors with `tf.variable`

In [ ]:
# create a tensor with tf.variable
changeable_tensor = tf.Variable([10,3])
unchangeable_tensor = tf.constant([20,5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([20,  5], dtype=int32)>)